### ISSUE TITLE
benchden sample estimates

### ISSUE THREAD

**Issue by smsaladi** [hafen/ed#1]
Thanks for this great package. This may be rather trivial, but I'm having trouble reproducing the plot of the benchden benchmark densities with the true density superposed. The estimates are correct since I can plot them separately, but when overlaying them, something doesn't work out well.

Do you still have the snippet used to generate the figure? If so, would you be able to add that to `README.md`? It may be useful for others as well.

**Comment by hafen** [comment]
Sorry about that - I have added code to reproduce the plot in `README.md`.  Let me know if you have any issues.

**Comment by smsaladi** [comment]
Suggested a change and Thanks!
